### ISSUE TITLE
"attributes is not a function"

### ISSUE THREAD

**Issue by matthew-dean** [adamhaile/surplus#34]
I have this object
```js
const attributes = { "slash-color": "light", "text-color": "dark"}
return <div class={ $style.host } {...attributes}>...</div>
```
However, Surplus throws the error in the browser "attributes is not a function". Is this because it has to be S.data? In the example I see:
```js
var props = { type: "text" },
    input3 = <input {...props} />;
```
But this doesn't seem to work as expected.

**Comment by matthew-dean** [comment]
I was able to stop an error from happening by using `const attr = S.data(attributes)` with `{...attr}` buuut see: https://github.com/adamhaile/surplus/issues/35.

**Comment by matthew-dean** [comment]
Never mind, this is fixed as of beta3.

**Comment by adamhaile** [comment]
Spread objects weren't supported in 0.4 but are in 0.5.  You're right, docs match 0.5, since it's about to be released.  0.4 [didn't really have much in the way of docs](https://github.com/adamhaile/surplus/tree/5741f277f3bb95582e9149535cdff8eb4ebb3bbf).  Sorry for the confusion.

**Comment by matthew-dean** [comment]
Okay, regardless, this doesn't seem to work on 0.5 either?
